<template>
  <div
    class="page"
    style="width: 375px; height: 812px; background: #FFFFFF;"
  >
    <AppHeader class="ur-node" style="left: 0px; top: 0px; width: 375px; height: 56px; background: #FFFFFF;" />
    <span class="ur-node" style="left: 24px; top: 203px; width: 327px; height: 32px; font-size: 24px; font-weight: 600; color: #111111;">Profile</span>
    <AppInput class="ur-node" style="left: 24px; top: 284px; width: 327px; height: 48px; background: #F5F5F5; border-radius: 8px;" placeholder="输入" />
    <Button class="ur-node" style="left: 24px; top: 406px; width: 327px; height: 48px; background: #1677FF; color: #FFFFFF; border-radius: 8px; font-size: 16px; font-weight: 600;">确定</Button>
  </div>
</template>

<script setup lang="ts">
import AppHeader from '../../components/restored/AppHeader.vue'
import AppInput from '../../components/AppInput.vue'
import Button from '../../components/Button.vue'
/** Generated by ui-restore — editable. */
</script>

<style scoped lang="scss">
.page {
  position: relative;
  overflow: hidden;
  box-sizing: border-box;
}
.ur-node {
  position: absolute;
  box-sizing: border-box;
}
</style>
