<template>
  <div
    class="shared-root"
    style="width: 375px; height: 56px; background: #FFFFFF;"
  >
    <span class="ur-node" style="left: 16px; top: 16px; width: 80px; height: 24px; font-size: 18px; font-weight: 600; color: #111111;">App</span>
    <span class="ur-node" style="left: 335px; top: 16px; width: 24px; height: 24px; background: #EEEEEE; border-radius: 4px;"></span>
  </div>
</template>

<script setup lang="ts">
/** Shared component generated by ui-restore — editable. */
</script>

<style scoped lang="scss">
.shared-root {
  position: relative;
  overflow: hidden;
  box-sizing: border-box;
}
.ur-node {
  position: absolute;
  box-sizing: border-box;
}
</style>
