import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import type {
  UiComponentDef,
  UiDocument,
  UiRestoreConfig,
} from '@ui-restore/shared'
import {
  matchDocumentToIndex,
  type ComponentIndex,
} from '@ui-restore/scanner'
import { collectComponentImports, renderNode } from './render.js'

export interface GenerateVueOptions {
  /** Project root (cwd of the target Vue app). */
  projectRoot: string
  /** Absolute or project-relative pages dir from config. */
  pagesDir: string
  lang: UiRestoreConfig['lang']
  style: UiRestoreConfig['style']
  index: ComponentIndex
  /** When true, skip matching (assume componentRef already set). */
  skipMatch?: boolean
}

export interface GenerateVueResult {
  filePath: string
  matched: UiDocument
}

export interface GenerateSharedOptions {
  projectRoot: string
  sharedDir: string
  lang: UiRestoreConfig['lang']
  style: UiRestoreConfig['style']
  /** Project component index for nested project refs inside shared roots. */
  index: ComponentIndex
}

function toPosix(p: string): string {
  return p.replace(/\\/g, '/')
}

function importPath(fromFile: string, componentFile: string): string {
  let rel = toPosix(relative(dirname(fromFile), componentFile))
  if (!rel.startsWith('.')) rel = `./${rel}`
  return rel
}

function styleBlock(
  style: UiRestoreConfig['style'],
  rootClass: 'page' | 'shared-root',
): string {
  const lang =
    style === 'scss' || style === 'module-scss'
      ? ` lang="scss"${style === 'module-scss' ? ' module' : ''}`
      : ''
  return `<style scoped${lang}>
.${rootClass} {
  position: relative;
  overflow: hidden;
  box-sizing: border-box;
}
.ur-node {
  position: absolute;
  box-sizing: border-box;
}
</style>
`
}

function buildImports(
  outFile: string,
  names: string[],
  index: ComponentIndex,
  projectRoot: string,
): string[] {
  return names.map((name) => {
    const entry = index[name]
    const abs = resolve(projectRoot, entry.path)
    return `import ${name} from '${importPath(outFile, abs)}'`
  })
}

/**
 * Generate shared component SFCs and return index entries to merge.
 */
export async function generateSharedComponents(
  defs: UiComponentDef[],
  options: GenerateSharedOptions,
): Promise<ComponentIndex> {
  const sharedRoot = resolve(options.projectRoot, options.sharedDir)
  mkdirSync(sharedRoot, { recursive: true })
  const sharedIndex: ComponentIndex = {}
  const scriptLang = options.lang === 'ts' ? ' lang="ts"' : ''

  // First pass: register paths so shared can import each other later if needed.
  for (const def of defs) {
    const rel = toPosix(relative(options.projectRoot, resolve(sharedRoot, `${def.name}.vue`)))
    sharedIndex[def.name] = {
      name: def.name,
      path: rel,
      export: 'default',
      props: [],
    }
  }

  const mergedIndex: ComponentIndex = { ...options.index, ...sharedIndex }

  for (const def of defs) {
    const outFile = resolve(sharedRoot, `${def.name}.vue`)
    const root = def.root
    const nestedImports = collectComponentImports(
      root.children ?? [],
      mergedIndex,
      'any',
    ).filter((n) => n !== def.name)

    // Also allow root itself to be a project component wrapper — render children inside relative root.
    const childXml = (root.children ?? [])
      .map((n) => renderNode(n, { index: mergedIndex, indent: '    ' }))
      .join('\n')

    const importLines = buildImports(outFile, nestedImports, mergedIndex, options.projectRoot)
    const bg = root.style?.background
      ? ` background: ${root.style.background};`
      : styleObjectBackground(root)

    const sfc = `<template>
  <div
    class="shared-root"
    style="width: ${root.box.width}px; height: ${root.box.height}px;${bg}"
  >
${childXml}
  </div>
</template>

<script setup${scriptLang}>
${importLines.length ? `${importLines.join('\n')}\n` : ''}/** Shared component generated by ui-restore — editable. */
</script>

${styleBlock(options.style, 'shared-root')}`

    writeFileSync(outFile, sfc, 'utf8')
  }

  return sharedIndex
}

function styleObjectBackground(root: UiComponentDef['root']): string {
  if (!root.style) return ''
  const { background } = root.style
  return background ? ` background: ${background};` : ''
}

/**
 * Generate a Vue SFC page from a validated UiDocument + ComponentIndex.
 */
export async function generateVuePage(
  doc: UiDocument,
  options: GenerateVueOptions,
): Promise<GenerateVueResult> {
  const matched = options.skipMatch ? doc : matchDocumentToIndex(doc, options.index)
  const pagesRoot = resolve(options.projectRoot, options.pagesDir)
  const outFile = resolve(pagesRoot, matched.page.id, 'index.vue')
  mkdirSync(dirname(outFile), { recursive: true })

  const imports = collectComponentImports(matched.page.children, options.index, 'any')
  const importLines = buildImports(outFile, imports, options.index, options.projectRoot)

  const scriptLang = options.lang === 'ts' ? ' lang="ts"' : ''
  const childrenXml = matched.page.children
    .map((n) => renderNode(n, { index: options.index, indent: '    ' }))
    .join('\n')

  const bg = matched.page.background
    ? ` background: ${matched.page.background};`
    : ''

  const sfc = `<template>
  <div
    class="page"
    style="width: ${matched.page.width}px; height: ${matched.page.height}px;${bg}"
  >
${childrenXml}
  </div>
</template>

<script setup${scriptLang}>
${importLines.length ? `${importLines.join('\n')}\n` : ''}/** Generated by ui-restore — editable. */
</script>

${styleBlock(options.style, 'page')}`

  writeFileSync(outFile, sfc, 'utf8')
  return { filePath: outFile, matched }
}

/** @deprecated Use generateVuePage */
export async function generateVue(
  doc: UiDocument,
  outDir: string,
): Promise<void> {
  await generateVuePage(doc, {
    projectRoot: outDir,
    pagesDir: '.',
    lang: 'ts',
    style: 'css',
    index: {},
  })
}

export function mergeComponentIndex(
  base: ComponentIndex,
  extra: ComponentIndex,
): ComponentIndex {
  return { ...base, ...extra }
}

export const generatorPackage = '@ui-restore/generator' as const
